CC = g++
CFLAGS = -std=c++11
SOURCES = main.cpp
EXECUTABLE = pushbox

all : $(CC) $(CFLAGS) -o $(EXECUTABLE) $(SOURCES) -lncursesw	# g++ -std=c++11 -o pushbox main.cpp -lncursesw

clean : $(RM) *.o $(EXECUTABLE)
